### ISSUE TITLE
Font block syntax error on compile with Red 0.6.4

### ISSUE THREAD

**Issue by anzellai** [hako/lines#2]
Since Red 0.6.4 is out, I have tested and find out it breaks the current repo on running.

Error as is:
>>>red/lines - [master] » red Lines.red
*** Script Error: VID - invalid syntax at: [14 font-color: white]
*** Where: do
*** Stack: view layout layout cause-error 

PR created: https://github.com/hako/lines/pull/1

By the way, I have been learning Red, and your repo is a great learning sample of how to make use of JSON data types <-> Red data types.

**Comment by hako** [comment]
Tested and merged PR #1, thanks for fixing this issue @anzellai, glad this repo helped you!
